//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comb.dat.
        /// </summary>
        internal static string combpath {
            get {
                return ResourceManager.GetString("combpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut key {0} has been cancelled!.
        /// </summary>
        internal static string cutext {
            get {
                return ResourceManager.GetString("cutext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination Unbound.
        /// </summary>
        internal static string cutitle {
            get {
                return ResourceManager.GetString("cutitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display config has changed. Press current key combination again to minimize wins..
        /// </summary>
        internal static string dcctext {
            get {
                return ResourceManager.GetString("dcctext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Config Changed!.
        /// </summary>
        internal static string dcctitle {
            get {
                return ResourceManager.GetString("dcctitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Key Combination Bound.
        /// </summary>
        internal static string defaultcap {
            get {
                return ResourceManager.GetString("defaultcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo Pressed.
        /// </summary>
        internal static string keypressed {
            get {
                return ResourceManager.GetString("keypressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to had all wins minimized.
        /// </summary>
        internal static string minimized {
            get {
                return ResourceManager.GetString("minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now press {0} to minimize windows!.
        /// </summary>
        internal static string nstext {
            get {
                return ResourceManager.GetString("nstext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Shortcut Established.
        /// </summary>
        internal static string nstitle {
            get {
                return ResourceManager.GetString("nstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am here. Double click me to resume or right click for menu!.
        /// </summary>
        internal static string ntrtext {
            get {
                return ResourceManager.GetString("ntrtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimized to Tray.
        /// </summary>
        internal static string ntrtitle {
            get {
                return ResourceManager.GetString("ntrtitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon sb233 {
            get {
                object obj = ResourceManager.GetObject("sb233", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Key Changed.
        /// </summary>
        internal static string shortcutchanged {
            get {
                return ResourceManager.GetString("shortcutchanged", resourceCulture);
            }
        }
    }
}
